<resource schema="EXOTOPO">
  <meta name="title">Topography of Exoplanets </meta>
  <meta name="description" format="plain"> 
The data consists in topographic maps of synthetic 3D bodies generated by a 3 parameters statistical model : the fractionally
integrated flux (FiF) (Lavallée et al 1993) adapted for in spherical coordinates (Landais et al., 2018).

The 3 parameters are the following :

H 	: degree of smoothness
C1 	: degree of intermittency
alpha 	: degree of multifractality

some example of the model output.The synthetic topographic maps consist in 5000x10000 lat-long grids that contained elevation data. Combined to a radius that can be freely chosen, each grid may be used to construct a 3-D shape of a planet-like or asteroid-like body. 

We aimed to illustrate the impact of a variation of H (degree of roughness) and C1 (degree of intermittency) for a typical value
of alpha (alpha=2). Hence each map has alpha = 2, H = {0.4 0.7 1.0} and C1 ={0.00 0.05 0.10}. 
compute the same simulations with various random seed  (S=01, 02, 03....).

Two kind of files are present :

1) hdf5 files containing topographic map represented as a lat-long grid. 
Topography nomenclature : S{seed id}_A{value of alpha x10}_C{value of C1 x100}_H{value of H x10}_LAT{latitude sampling}_LON{longitude sampling}_TOPO.hdf5
 
 2) hdf5 files containing texture map to be applied on the topography. As our statistical model mainly consists in a control of roughness at different scales and location, the main goal of the texture map is to be visually significant in terms of roughness, reflecting the juxtaposition of rough and smooth places. We make use of the classic method of Hill-shading that consists in computing the scalar product between local slopes and a constant light direction. Given the spherical geometry, only a portion of the synthetic body can be clearly visible under a specific light direction. For each topographic map we provide hill-shade textures in an arbitrarily chosen light direction . For H=1, the colormap is as a shade of gray whereas for H&lt;1, it tends to reproduce the color of an earth-like planet. Additionally, we provide a texture colormap without hill-shading in each case. As a result, there are two distinct texture maps for each field with the following nomenclature :

Texture nomenclature : S{seed id}_A{value of alpha x10}_C{value of C1 x100}_H{value of H x10}_LAT{latitude sampling_LON{longitude sampling}{"COLO"  or "GRAY"}["SHADE" or "FLAT"].hdf5   	    
 </meta>
 
  <meta name="creationDate">2020-09-14T09:42:00Z</meta>
  <meta name="subject">Planet</meta>
  <meta name="subject">Exoplanet</meta>
  <meta name="subject">Topography</meta>
  <meta name="subject">Simulation</meta>
  <meta name="subject">Multifractal</meta>
  <meta name="subject">Roughness</meta>
  <meta name="copyright">GEOPS</meta>
  <meta name="creator.name">Chloe Azria</meta>
  <meta name="publisher">IPSL/GEOPS</meta>
  <meta name="contact.name"> </meta>
  <meta name="contact.email">vo.paris@obspm.fr</meta>
  <meta name="contact.address">GEOPS, batiment 339 Rue du Belvedere Campus Universitaire d'Orsay 91400 Orsay</meta>
  <meta name="source">Dataset DOI: 10.14768/20181024001.1 ;
  			link: https://data.ipsl.fr/catalog/srv/eng/catalog.search#/metadata/60110bbd-e7f1-4d03-9e84-7ac38feb2499</meta>
  <meta name="contentLevel">University</meta>
  <meta name="contentLevel">Research</meta>
  <meta name="utype">ivo://vopdc.obspm/std/EpnCore#schema-2.0</meta>
<!-- METADATA COMPLETE -->



  <table id="epn_core" onDisk="true" adql="True" primary="granule_uid">
	<mixin spatial_frame_type="spherical"
		optional_columns= "access_url access_format access_estsize time_scale publisher bib_reference" >
		//epntap2#table-2_0
	</mixin>

	<column name="filename"  
		type="text"
		tablehead="filename"
		description="relative path" 
		verbLevel="3"/>

	<column name="random_seed"  
		type="text"
		tablehead="random_seed"
		description="The identifier of the random seed"
		verbLevel="1"/>

	<column name="alpha"  
		type="double precision"
		tablehead="alpha"  
		unit=""
		description="Degree of multifractality"
		verbLevel="1"/>

	<column name="c1"  
		type="double precision"
		tablehead="c1"  
		unit=""
		description="Degree of intermittency"
		verbLevel="1"/>

	<column name="H"  type="double precision"
		tablehead="H"  unit=""
		description="Degree of smoothness"
		verbLevel="1"/>
		
	<column name="Latitude_Sampling"  
		type="double precision"
		tablehead="Latitude_Sampling"  
		unit=""
		description="Latitude_Sampling"
		verbLevel="15"/>
		
	<column name="Longitude_Sampling"  
		type="double precision"
		tablehead="Longitude_Sampling"  
		unit=""
		description="Latitude_Sampling"
		verbLevel="15"/>
		
	<column name="type"  
		type="text"
		tablehead="type"  
		unit=""
		description="describe the content of the file TOPO: topographic data; {GRAY|COLO}{SHAD|FLAT}: texture files respectively  {Shades of grey|Earth-like colorscale}{Shadow|Flat}"
		verbLevel="2"/>
  </table>



<!-- TABLE COMPLETE -->

  <data id="import">
	<sources>data/metadata.csv</sources>
	<csvGrammar>
		<rowfilter procDef="//products#define">
			<bind name="table">"\schema.epn_core"</bind>
			<code>
				if "TOPO" in @type :
					@access_estsize=400000
				else :
					@access_estsize=150000
				yield row
			</code>
		</rowfilter>			
	</csvGrammar>

	<make table="epn_core">
		<rowmaker idmaps="*">
			<var key="dataproduct_type">"vo"</var> <!-- volume: 3d structures-->
			<var key="spatial_frame_type">"spherical"</var> <!-- or body ?-->

		<!--varying valued columns-->
		<!-- <var key="[column name 1]" source="[source column name]"> -->
			<var key="target_name" source="filename" />
			<!--+ tard s_H_C car plusieurs obs d'une meme source-->
			<var key="granule_uid" source="filename" />
			<var key="granule_gid" source="type" />
								
		<!--constant valued columns-->
		<!-- <var key="[column name 1]">"[value]"</var> -->
			<var key="obs_id"> @filename[0:15]</var>
                       <var key="access_url">"file:///var/gavo/inputs/EXOTOPO"+@filepath+@filename</var>
			<var key="access_format">"application/x-hdf"</var>
			<!--<var key="access_estsize">400000</var>--><!--400 MB fichiers TOPO , 150 MB shad flat-->				
			<var key="service_title">"EXOTOPO" </var>				
			<var key="creation_date">"2020-09-15T07:54:00.00" </var>
			<var key="modification_date">"2020-09-15T17:54:00.00" </var>
			<var key="release_date">"2020-09-15T07:54:00.00" </var>


			<var key="bib_reference">"Topography of (exo)planets F.Landais, F.Schmidt, S.Lovejoy. doi:10.1093/mnras/sty3253"</var>
			<var key="publisher">"GEOPS, IPSL" </var>


			<apply procDef="//epntap2#populate-2_0" name="fillepn">
				<bind name="granule_gid">@granule_gid</bind>
				<bind name="granule_uid">@granule_uid</bind>
				<bind name="obs_id">@obs_id</bind>
				
				
				<bind name="target_class">"planet"</bind>
				<bind name="time_scale">"UTC"</bind>
				<bind name="target_name">@target_name</bind>
				<bind name="instrument_host_name">""</bind>
				<bind name="instrument_name">""</bind>
				
				<bind key="processing_level">5</bind> 
				<bind name="dataproduct_type">@dataproduct_type</bind>
				<!-- <bind name="access_estsize">@access_estsize</bind>-->
				
				<bind name="service_title">@service_title</bind>
				<bind name="creation_date">@creation_date</bind>
				<bind name="modification_date">@modification_date</bind>
				<bind name="release_date">@release_date</bind>

			</apply>
		</rowmaker>
	</make>
  </data>
</resource>
